### ISSUE TITLE
Loomio

### ISSUE THREAD

**Issue by gdpelican** [rails-girls-summer-of-code/projects#11]
**Name and Contact of the Primary Project Mentor:** James Kiesel (james@loomio.org)
**Name of the Project:** Loomio
**URL:** http://www.loomio.org
**Github:** https://github.com/loomio/loomio

**About the Project:**
Loomio is an online tool for collaborative decision-making developed by a small team in New Zealand and used by activists, local governments, student groups and communities worldwide. It has been translated into over 30 languages, and is currently in use by the Podemos movement in Spain, the open source social network Diaspora*, and the statistics branch of the New Zealand government.

**What are issues/features students may work on?:** 
We maintain a well-curated and up-to-date issues list on github - those marked 'Please help' we're particularly keen to review PRs on. There is also an active open source translation community on Transifex, which allows for translation contributions. (more info on that at https://github.com/loomio/loomio/wiki/Translation)

**Suitable for beginners:** Yes, we mark issues suitable for beginners as 'Easy Win', and are very responsive to new open sourcers.

Feel free to reach out with any additional questions.

Thanks!

**Comment by lislis** [comment]
So cool :+1:

**Comment by anikalindtner** [comment]
<3 thank you so much for submitting, @gdpelican!

**Comment by Neethusajeevan** [comment]
Hi @gdpelican 
myself Neethu @Neethu_sajeevan and Ameera @pohameera are intrested in working on your project

**Comment by Xteff** [comment]
Hi, @anxhe and I @freewomancode are also interested in working on your project.

**Comment by soff22** [comment]
Dear James,
me and my teammate Boryana are much interested in your project. Actually, we would love to work on something similar. We would like to apply for it and I do hope it is not too late.
Please inform me if we can participate and join you.
Thank you
Kind regards,
The RailsGiEnthusiasts Team

**Comment by alicetragedy** [comment]
#### Students: please don't apply for this project anymore :)
