### ISSUE TITLE
Rails Girls Summer of Code: The Teams App

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/projects#12]
**Name and Contact of the Project Mentor**: Carsten Zimmermann <carsten@railsgirlssummerofcode.org>

**Name of the Project**: RGSoC Teams App

**URL**: http://teams.railsgirlssummerofcode.org ([source code](https://github.com/rails-girls-summer-of-code/rgsoc-teams))

**About the Project**:
The Teams App is the main hub for all RGSoC participants: students, supervisors and organizers alike. This is where students form teams, apply for the Rails Girls Summer of Code and update their team status. Organizers use the app to support them in their selection process and to generally keep up to date with the current status of the summer's participants (the latter is especially true for supervisors).

The teams app has evolved since its initial 2013 incarnation and we want to make it an even better tool to help us in the Rails Girls Summers of Code to come :smile: 

**What are issues/features students may work on?**:
We have [prepared a selection of Github issues](https://github.com/rails-girls-summer-of-code/rgsoc-teams/labels/rgsoc-2015) we would like to tackle over the course of the summer. Two major milestones would be a »tactical overview« for supervisors and organizers as well as finalising the move to an application that will know about its different phases throughout the year (i.e. pre-application, application-phase, the three months in the summer, post-RGSoC).

**Suitable for beginners?**: 
Yes, very much so! We [have a subset of issues](https://github.com/rails-girls-summer-of-code/rgsoc-teams/labels/beginner-friendly) we consider especially beginner-friendly.

**Comment by lislis** [comment]
:heart: :heart: :heart:

**Comment by anikalindtner** [comment]
:sparkles: :sparkles: :sparkles: :sparkles:

**Comment by emcoding** [comment]
Team Cheesy says hello! To our mentor & project. Yay!

**Comment by roosdebildt** [comment]
Like! <3
