### ISSUE TITLE
Speakerinnen

### ISSUE THREAD

**Issue by tyranja** [rails-girls-summer-of-code/projects#14]
**Name and Contact of the Project Mentors:** Maren (Twitter: @zaziemo) and Anja (Twitter: @_tyranja_ ), email: speakerinnen@lists.riseup.net

**Name of the Project:** Speakerinnen List

**URL:** https://speakerinnen.org/

**Github:** https://github.com/rubymonsters/speakerinnen_liste

**About the Project:** The Speakerinnen List aims to increase the visibility and participation of women at conferences, panels and talk shows. Organizers and hosts can find experts, who share their knowledge.
Women can register in our database with the topics they are interested in covering.
The Project is made and maintained by woman of a RailsGirlsGroup called the rubymonsters. 

**Suitable for beginners?** Yes, since we are all more or less beginners here ;)

**What are issues/features students may work on?** Right now there is a big issue with tag translation and admin testing and lots of smaller issues as you can see on github.

**Comment by lislis** [comment]
amazing :D

**Comment by anikalindtner** [comment]
Thanks so much @tyranja for submitting! :yellow_heart:

**Comment by alicetragedy** [comment]
cooooooooooooool! :tada:

**Comment by essymo** [comment]
Hi @tyranja my teammate (@Ressy77) and I would like to work on your project

**Comment by tyranja** [comment]
Hej Maren,

hast Du auch die mail bekommen? Was soll ich nu darauf antworten?

Was habt ihr heute gemacht? Wir haben 40 Eier gefärbt :) Auch ein Erfolg!


Anja

**Comment by zaziemo** [comment]
@essymo & @Ressy77 yay! Great to hear that. I would be glad to be your mentor and help you to pick some issues so that you can fix your project plan for the application. Here you'll get an overview over the current issues (will be updated in the next days): https://github.com/rubymonsters/speakerinnen_liste/issues/216 Probably it would be good to set up a skype call or hangout next week.

**Comment by anikalindtner** [comment]
#### Students: please don't apply for this project anymore.
