### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by orta** [rails-girls-summer-of-code/projects#15]
**Name and Contact of the Project Mentor**: Orta Therox orta@cocoapods.org, Kyle Fuller kyle@cocoapods.org, Samuel Giddins sam@cocoapods.org ( All can be contacted via info@cocoapods.org )

**Name of the Project:** CocoaPods 

**URL:** http://cocoapods.org | http://github.com/cocoapods/cocoapods

**About the Project:**
CocoaPods is the Objective-C / Swift dependency manager. Doing the work of both Rubygems and Bundler. It's used by almost all iOS projects, and is written in ruby as a collection of gems. We have a both a collection of labeled issues for getting started, and a collection of atomic larger features that can be built independently with mentors in our [Summer of Code page](http://cocoapods.org/summer-of-code-2015).

**What are issues/features students may work on?:**
We have prepared a selection of Github issues we would like to tackle over the course of the summer linked above, and have a tag specifically for [easy tickets](https://github.com/CocoaPods/CocoaPods/labels/d1%3Aeasy) when bootstrapping.

**Suitable for beginners?:**
Yes, we regularly get [core contributors](http://blog.cocoapods.org/starting-open-source/) from the Objective-C world with no ruby experience.

**Comment by anikalindtner** [comment]
yay! thanks for submitting @orta!

**Comment by anikalindtner** [comment]
aaannnnnd APPROVED! great work, and I'm looking forward to see what's happening over the summer <3

**Comment by orta** [comment]
:palm_tree: :balloon: :palm_tree:

**Comment by Neethusajeevan** [comment]
Hi @orta , I Neethu @Neethusajeevan and ameera @pohameera are intrested in your project. we have also sent you an email. We would like to apply for it and I do hope it is not too late.
Please inform me if we can participate and join you.
Thank you
Kind regards,
Neethu

**Comment by emkosz** [comment]
Hi @orta ! My friend @Karla-Isabel-Sandoval and I are also interested in CocoaPods and have sent you an email. 
Best regards,
Emma and Karla

**Comment by kinjalgada** [comment]
Hi @orta ! I and my pair @AniShah are interested in working with you. Are you'll still accepting students? We're based in Mumbai. We already have our coach based in Mumbai as well. We'll send you an email :)

**Comment by alicetragedy** [comment]
We're sorry @kinjalgada and @AniShah, applications for RGSoC closed 7 hours ago (April 14th, 23:59 UTC) so it's not possible to submit an application anymore. You can always give it a try next year! :tada:
