### ISSUE TITLE
RailsAdmin

### ISSUE THREAD

**Issue by sferik** [rails-girls-summer-of-code/projects#16]
**Name and Contact of the Project Mentor:** Erik Michaels-Ober, @sferik, sferik@gmail.com

**Name of the Project:** RailsAdmin

**URL:** https://github.com/sferik/rails_admin

**About the Project:** RailsAdmin is a Rails engine that provides an easy-to-use interface for managing data.

**Suitable for beginners?** Yes. RailsAdmin was originally developed by a student as part of the 2010 Ruby Summer of Code, with me acting as a mentor.

**What are issues/features students may work on?** The project currently has over 200 open issues and 40 open pull requests, so there’s a lot of work that can be done. Including many small tasks. There are other things (aside from issues) that beginners can work on as well, for example, building and designing a marketing website for RailsAdmin, or improving the online demo. I also think RailsAdmin is due for a redesign and maybe even an entire rewrite, depending on how ambitious the team is.

**Comment by anikalindtner** [comment]
whoooop!! <3 <3 <3

**Comment by alicetragedy** [comment]
yay, thank you for your submission @sferik :balloon:

**Comment by darzh** [comment]
@sferik Hello Erik! My teammate (@VesSun) and I would like to join your project. Are there any more places open? We will send a separate email to discuss it in details. Talk to you soon. -Dari

**Comment by gabrielanavarro** [comment]
Hello @sferik, I would like to participate in this project. Can you tell what I should do to participate? :)

**Comment by sferik** [comment]
Hi all. Feel free to submit your application with this project. I will only have time to mentor the team that is selected by the Rails Girls Summer of Code organizers.
