### ISSUE TITLE
Twitter CLI

### ISSUE THREAD

**Issue by sferik** [rails-girls-summer-of-code/projects#17]
**Name and Contact of the Project Mentor:** Erik Michaels-Ober, @sferik, sferik@gmail.com

**Name of the Project:** Twitter CLI

**URL:** https://github.com/sferik/t

**About the Project:** A command-line power tool for Twitter.

**Suitable for beginners?** Yes.

**What are issues/features students may work on?** The students would be reimplementing the existing Twitter command-line interface in the Crystal programming language. Crystal is a language with similar syntax to Ruby but with many optimizations that make it a better choice for CLIs. The current Ruby implementation would serve as a working specification of the correct behavior. There is also a comprehensive spec suite with 590 examples (99.3% coverage).

I originally wasn’t planning to submit this project but then @janl [tweeted](https://twitter.com/janl/status/572806210895912960) that it didn’t need to be a Ruby project, so here it is. I would be very excited to coach a team on Crystal and, of course, teaching some Ruby would be necessary as well. Perhaps @asterite or @waj would be interested to serve as remote mentors. That would be awesome!

**Comment by asterite** [comment]
@sferik Thanks for this submission! I would be more than happy to mentor this! :smile:

**Comment by svenfuchs** [comment]
:heart:

**Comment by anikalindtner** [comment]
thanks so much @sferik for this and @asterite for volunteering to co-mentor! ACCEPTED! :heart: :yellow_heart: :blue_heart:

**Comment by alicetragedy** [comment]
:sparkles:

**Comment by ashlesha10** [comment]
Hi,
Me and my partner Rohini interested in project could you please provide us guideline how to proceed further.

**Comment by claucece** [comment]
Hi! Me and my partner Evy are interested in this project! :)

**Comment by anila1995** [comment]
Hi,
I and my partner Monija are interested in doing this project. Kindly let us know more  about the knowledge and abilities you expect from the students to do this project.

**Comment by isatorri** [comment]
Hi, Erik!

We would like to work with your project, is it still possible? I also sent you an email, but I thought that a message here would work as well :) Please, let us know.

**Comment by gabrielanavarro** [comment]
Hi Erik,

I would like to work with your project. Can you tell me what should I do to participate?

**Comment by sferik** [comment]
Hi all. Feel free to submit your application with this project. I will only have time to mentor the team that is selected by the Rails Girls Summer of Code organizers.
