### ISSUE TITLE
Spring Data

### ISSUE THREAD

**Issue by odrotbohm** [rails-girls-summer-of-code/projects#18]
- **Name and Contact of the Project Mentor:** [Oliver Gierke](https://github.com/olivergierke)
- **Name of the Project:** Spring Data
- **URL:** http://projects.spring.io/spring-data
- **About the Project:** Spring Data is an umbrella project to provide a programming model for data access on the Java platform on top of Spring Framework. I makes it easy for Java developers to interact with various relational and non-relational databases by exposing a programming model that leverages core concepts of Domain Driven Design. For a quick impression, check out our [getting started guide for the JPA module](https://spring.io/guides/gs/accessing-data-jpa/).
- **Suitable for beginners?** Yes, depending on the experience with mostly Java, Maven and/or Asciidoctor we can find suitable tasks for participants.
- **What are issues/features students may work on?** Of course, improving the project's reference documentation is something very valuable to the community. For more experienced participants we can also find more technically challenging tasks like tweaking the project build for Spring Data MongoDB to use an in-process instance of MongoDB (see [this ticket](https://jira.spring.io/browse/DATAMONGO-1171) for details). Generally speaking, we're totally open for participants preferences and are sure to find something interesting to work on.

A core aspect of the work will be getting used to the way an open-source project backed and maintained by a professional company is developed. Participants will be included in planning hangouts, the core development process, team collaboration and release execution

**Comment by alicetragedy** [comment]
Hi @olivergierke, thank you for submitting Spring Data as a project for this year's RGSoC and congratulations on being accepted! :balloon:

**Comment by odrotbohm** [comment]
Awesome, looking forward to it! :tada:

**Comment by PetyaPanayotova** [comment]
@olivergierke is there still an opportunity for joining the project? :)

**Comment by odrotbohm** [comment]
@PetyaPanayotova - Yes there is. I guess we gotta hurry up as the deadline's near but we should be able to sort this out one way or the other. Drop me an email with the organizers CCed?
