### ISSUE TITLE
Hoodie

### ISSUE THREAD

**Issue by janl** [rails-girls-summer-of-code/projects#19]
_Name and Contact of the Project Mentor:_
Jan Lehnardt @janl jan@apache.org (with other community members helping out)

_Name of the Project:_
Hoodie

_URL:_
http://hood.ie

_About the Project:_
Hoodie is a web application back-end with a beginner friendly frontend JavaScript API.

_Suitable for beginners?_ 
Yes.

_What are issues/features students may work on?_

Hoodie consists of many sub-projects (https://github.com/hoodiehq/) and possible activities are wide ranging:
- **Documentation:** We are always in need of improving our documentation, adding API docs, tutorials, screencasts etc.
  - Documentation translation: We believe that localised documentation is a form of accessibility, so we are looking for many people who can translate the Hoodie documentation into their native language.
  - The applicants will learn about Hoodie itself and then transfer their knowledge into our various documentation systems including screencasts. We’d tutor on writing good docs, using different documentation systems.
- **Frontend JavaScript:** The main hoodie.js module is in constant need of a cleaner code-base and more features.
  - Applicants will learn about Frontend JavaScript, API design (“Dreamcode”), through testing, basic, API documentation and Hoodie itself.
- **Backend JavaScript:** Hoodie’s backend is in constant need of cleaner code and more features. It is written in Node.js and makes critical use of Apache CouchDB.
  - Applicants will learn about Node.js, CouchDB, framework design, thorough testing, cross-platform (Unix/Linux/Mac/Windows) development as well as Node.js design patterns, the hapi HTTP framework, evented programming, security and documentation.
- **Plugins:** Hoodie’s core is relatively small and most core functionality is implemented via plugins. Plugins allow e.g. interfacing with other services (like GitHub, or payment providers, etc.). Plugins can also be pure frontend-utilities that implement a certain feature. Plugins can also contain a administration dashboard component, that allows application admins to change certain properties of the running app (like the outgoing mailserver, or oauth providers etc).
  - Applicants will learn about Hoodie itself and the extensive plugin system. They have a choice of frontend, backend and user interface programming. They will learn about system integration, evented programming, ui programming, testing and security.

As we are constantly helping people new to Hoodie anyway, we are happy to provide support for RGSoC applicants, even if they are new to JavaScript. The above areas of work are rather vague, but we don’t know yet which specific things are on the roadmap in summer. We are tracking all project issues here: http://espy.github.io/ubersicht/#hoodiehq

**Comment by anikalindtner** [comment]
:sparkles: :sparkles: :sparkles:  :heart:  woah! :sparkles: :sparkles:

**Comment by alicetragedy** [comment]
:heart_eyes:

**Comment by svenfuchs** [comment]
:heart:

**Comment by anikalindtner** [comment]
accepted!! thanks for submitting <3

**Comment by anikalindtner** [comment]
##### Students: please don't apply for this project anymore!
