### ISSUE TITLE
BalaSwecha - Bridging the digital divide

### ISSUE THREAD

**Issue by SrujanaMehra** [rails-girls-summer-of-code/projects#20]
**Name of the Project**: BalaSwecha

**About the project:**
BalaSwecha is a learning platform for school children from the underprivileged background, which provides them with virtual lab environment and multimedia content. This helps students explore their subjects better and even encourage them to explore beyond their textbooks. BalaSwecha is a tool which complements teachers but not replace teachers.

The main aim of this project is to bridge the growing digital divide at the school education level, clearly visible between schools for the underprivileged and corporate schools.

BalaSwecha as a learning platform is used by students and teachers where they interact with and learn through the applications. Subjects like physics, chemistry and mathematics, which are to be learnt by conducting experiments can be explored by using the applications present in BalaSwecha operating system.

_Here is an article about the project: http://www.thoughtworks.com/insights/blog/bridging-digital-divide-underprivileged-communities_

**Why work on this project?** 
Firstly, you will be working on the latest technologies like HTML5, CSS3 and Angular JS. In projects like BalaSwecha you are directly impacting the society. You can get the feedback from the kids who are using the application. It will be one amazing experience to see the glow on their face when they are using these applications made by you!

**Product Development:**
There has been a continuous effort into product development. The team is working on developing more educational applications, building a complete learning management tool and making BalaSwecha work on open hardware.

Technologies used for product development are HTML5, CSS3 and AngularJS.

**Constraints:**
The constraints for product development are, most of the schools are equipped with:
Low end hardware like 128 MB RAM  
N Computing     devices are the proprietary devices with expired licences for the     Windows Operating Systems.     

**Implementation:**

Conducting Teacher Training Workshops (TTW) helped in taking BalaSwecha forward. In our TTW Edition -1, there were around 180 teachers from 100 different Government schools across two states in India who have taken part.

TTW Edition – 2 mainly concentrated on training the Master Resource Persons (MRP). The idea is MRP will conduct classes to the Government school teachers in each district.

_Read more at: http://swecha.org/content/teacher-training-workshop-ed-2_

In summer of 2015, we will be conducting a workshop from teachers and also conduct a summer camp for the students for the first time.

_Suitable for beginners?_
Yes, both beginners and experienced can work on it easily. 

**What are issues/features students may work on?**
Bug fixing 
Converting a few existing applications to HTML
Multimedia content 
Simulations for applications like Stellarium, celestia, STEP etc. 
Creating Mock ups for new applications 
New application development 

**Name and Contact of the Project Mentor**: Naga Sujan Mehra - +91 9966010916

**Technology mentor:**  Isha Tripathi (Application Developer, Bala Swecha Alumni) : “I personally have seen the gap between facilities and infrastructure available in government schools in India, it’s enough to discourage even the brightest of students from exploring further than what the textbooks give them. The teachers themselves do not have resources to help the students, if and when they want to. I see this is an excellent opportunity to help out”

**Git Repo:**
https://code.swecha.org/groups/balaswecha/

**Comment by lislis** [comment]
Hey @SrujanaMehra,  thanks for your proposal! I have  a few questions though.  
First one is about licencing: Where do you display under which open source licence each project is run? And if you don't have an open source licence for each project yet, please add one as they're required for projects to participate in Rails Girls Summer of Code.
The seconds question is about the ssl certificate on your Gitlab page. It seems to be broken and the resulting warning in the browser might scare away people who want to take a look at the code. Do you plan on fixing that in the near future?

**Comment by SrujanaMehra** [comment]
Hi Lisa,

First one is about licencing: Where do you display under which open source

> licence each project is run? And if you don't have an open source licence
> for each project yet, please add one as they're required for projects to
> participate in Rails Girls Summer of Code.

All the applications are under GPLv3. We will shortly put up the license
notice  on the project page.

The seconds question is about the ssl certificate on you Gitlab page. It

> seems to be broken and the resulting warning in the browser might scare
> away people who want to take a look at the code. Do you plan on fixing that
> in the near future?

We are renewing the SSL certificate, it should be up in next few days.

Thanks,

On Mon, Mar 9, 2015 at 9:33 PM, Lisa P notifications@github.com wrote:

> Hey @SrujanaMehra https://github.com/SrujanaMehra, thanks for your
> proposal! I have a few questions though.
> 
> First one is about licencing: Where do you display under which open source
> licence each project is run? And if you don't have an open source licence
> for each project yet, please add one as they're required for projects to
> participate in Rails Girls Summer of Code.
> The seconds question is about the ssl certificate on you Gitlab page. It
> seems to be broken and the resulting warning in the browser might scare
> away people who want to take a look at the code. Do you plan on fixing that
> in the near future?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/projects/issues/20#issuecomment-77882952
> .

## 

_Naga Srujana Mehra_

_Telephone+91 9966010916_[image: ThoughtWorks]
http://www.thoughtworks.com/

**Comment by alicetragedy** [comment]
Hi @SrujanaMehra, we're happy to accept the project for this year's summer of code! Congrats :tada: 
Please, if you have not done so yet, don't forget about the license and the SSL certificate. Thank you!

**Comment by alicetragedy** [comment]
@SrujanaMehra one more thing, before I forget – could you also give us a way to contact you by email? At some point we'd like to get in touch with all project mentors by email and will require an email address. Thank you!

**Comment by SrujanaMehra** [comment]
You can email me at nagamach@thoughtworks.com or 
Mehra@swecha.net

**Comment by anjalyes** [comment]
@SrujanaMehra me and my partner are interested in working in this project. Is it still open?
