### ISSUE TITLE
Drupal.org: Update novice documentation and getting involved guide

### ISSUE THREAD

**Issue by YesCT** [rails-girls-summer-of-code/projects#21]
## Name and Contact of the Project Mentor:

Cathy Theys
@YesCT
## Name of the Project:

Drupal.org: Update novice documentation and getting involved guide
## URL:

[Issue #2332789: Reduce Novice Contribution differences and consolidate landing pages, content, blocks](https://www.drupal.org/node/2332789) 
## About the Project:

Drupal is an open source content management system and framework with an active welcoming community that values new contributors.
## Suitable for beginners?

Yes. OK for people new to open source or new to Drupal.
### Description of issue

Update, re-organize, consolidate documentation. May include getting a drupal.org development server, an updating features in git to track changes to pages, blocks, menus, book structure.
### Skills (will be learned)

Patience, grammar, organization, UI, drupal.org issue queues, git, features, drupal 7, blocks, book module

**Comment by carpodaster** [comment]
Thank you, @YesCT, for proposing Drupal as a RGSoC project! :balloon: 

I understand you don't track your code / issues with Github – can you link a more extended list of issues students could work on? You mention a major documentation update. It would be nice to see a good focus on programming, rather than mainly working on the documentation.

That being said, I perfectly understand that updating the docs also involves reading and understanding code as well as installing a Drupal app. But maybe you also have a couple of code-related features that a RGSoC team could implement over the course of the summer?

**Comment by YesCT** [comment]
Drupal is a great open source project with many issues. :) And many issue queues:
- some around Core, 
  - https://www.drupal.org/project/issues/search/drupal (but the whole core queue is overwhelming)
  - https://www.drupal.org/project/issues/search/drupal?project_issue_followers=&status%5B%5D=8&version%5B%5D=8.x&issue_tags_op=%3D&issue_tags=Novice (so I like to filter it down to issues that are 8.x, needs review, and have the Novice tag)
  - https://www.drupal.org/core-mentoring (and we have programs to help people get involved)
- some around Drupal.org
  - https://www.drupal.org/project/project_drupalorg?filters=bs_project_sandbox%3A%5B%2A%20TO%20%2A%5D (all 42 D.o queues)
  - https://www.drupal.org/project/drupalorg (D.o customizations is an example of one D.o queue)
- some about "contrib" (plugins/extentions) projects.
  - https://www.drupal.org/project/project_module (modules)
  - https://www.drupal.org/project/project_theme (themes)

But I was just proposing this one scoped issue, not all our issues. :)

Yes. I had some hesitation about suggesting this issue about the Drupal getting involved guide since it is neither Rails, nor Code. But I remembered a tweet (which I cannot find now) that said projects did not need to be. https://twitter.com/YesCT/status/574973124162224128 I had originally listed this idea on the Drupal GSoC list. https://groups.drupal.org/node/455978 But those _must_ be code.

This issue would be more about UI and user interactions than documenting code. It is about organizing our getting involved guide. https://www.drupal.org/node/2332789 

I do have several other issues that are more code focused.
Some (which were not listed in GSoC):
https://www.drupal.org/node/2013222
which might cross with other context help issues like
https://www.drupal.org/node/2185511
But they might not be good for beginners.

some that are more contained in their scope:
- https://drupal.org/node/2225601 (component link)
- https://drupal.org/node/2232387 (follower AND)
- https://www.drupal.org/node/2362065 (sort tags. might be done before summer though. maybe.)
- and any of the children of https://www.drupal.org/node/951114 (making drupal.org work on all screen sizes)

I work on Drupal 8 core, but I also work on making it easier for people to get involved contributing to Drupal. So the particular issues I have pointed out are about the contributor experience, from a more systemic point of view, dealing with our main tool: drupal.org.

**Comment by carpodaster** [comment]
Thanks @YesCT for all the additional details :books: :smile:   We would really like to see students contributing actual code – I can totally see that happen :+1: 

Accepted!

**Comment by alicetragedy** [comment]
Hi @YesCT, we've got some announcements to make to all project mentors – how can I contact you by email? (alternatively you can drop us a line, our email is on the website in the section "Help Out": railsgirlssummerofcode.org)

thanks in advance!

**Comment by essymo** [comment]
Hello @YesCT My teammate(@Ressy77) and I would like to work on this project.kindly provide your email so we can easily get intouch

**Comment by YesCT** [comment]
Sure, reach out to me in irc. I'm YesCT on irc.freenode.net You can find me in #drupal.
