### ISSUE TITLE
SoundDrop - connecting audio to places

### ISSUE THREAD

**Issue by starkcoffee** [rails-girls-summer-of-code/projects#23]
**Name and Contact of the Project Mentors**
Duana (@starkcoffee on Twitter and Github) 
collaborating with Rails Girls alumni 
Brigitte (Twitter @gobridgego)
Michelle (Twitter @MichelleVerones) 
Caroline (Twitter @carolvnunes)
Tam (Twitter @travelingtamm)
and Tosca (Twitter @nanopodstudio), a metal and glass artist [doing an art residency in Iceland!](https://www.kickstarter.com/projects/491537605/artist-residency-studio-at-gullkistan-iceland)

Email: sounddrop@googlegroups.com

**Name of the Project** 
SoundDrop

**URL** 
http://sounddrop.audio

**Github**
https://github.com/cloudyMBC/sounddrop

**About the Project**
SoundDrop lets you record stories and connect them to a place where they belong - via QR code or geolocation. We are developing SoundDrop so that you can leave an audible mark yourself - anywhere. Be it that you wish to leave some kind of sound graffiti at the wall memorial. Or create an alternative museum tour? Tell a personal story about a famous landmark?

It was created by "CloudyMBC" – Rails Girls Michelle, Brigitte and Caroline during their [SoundCloud Rails Girls 2014 Internship](http://blog.soundcloud.com/2015/03/09/celebrating-rails-girls-at-soundcloud/).

It is a mobile website using Ruby on Rails, Javascript, HTML, CSS and MySQL.

**Suitable for beginners?**
Yes of course!

**What are issues/features students may work on?**
We are prototyping with Tosca to use SoundDrop for an outdoor exhibition. Just some ideas for features:
- add a page to describe a playlist
- let users find SoundDrops nearby .. this is a big feature but we'll help you all the way!

**Comment by alicetragedy** [comment]
hi @starkcoffee, thank you for submitting! Here's to an amazing RGSoC 2015! :tada:

**Comment by starkcoffee** [comment]
thanks @alicetragedy ! btw, what should I do if multiple teams request to work on the project?

**Comment by alicetragedy** [comment]
@starkcoffee we advise mentors to not take on more than 2-3 teams for a couple of reasons: one, so that you don't have an overload of work if they need help with their application and/or if all teams end up being accepted, and two, to also give other projects the chance to participate :)
If you think you have enough "teams on your plate" then comment in this issue (if possible saying how many teams have contacted you and will apply, so we have a rough idea) and we'll add the label "maximum applications reached" to the issue.
I'm going to send an email to all projects that have been accepted so far today, to give them details about this process, and will change the project guides on our website accordingly. thanks for asking!

**Comment by starkcoffee** [comment]
@alicetragedy thanks for your quick reply! I would prefer to work with just one team as this is a small project and coordination between different teams could be hard at this point. not sure how to choose which team to go with? and yes please mark this project as "maximum teams reached"

**Comment by alicetragedy** [comment]
@starkcoffee no problem :) it definitely makes sense to have just one team if it's a small project. Could you add that information to your description above? (that you'd prefer to only handle one team). 
As for the choice, realistically I think you should try and see which team you think can offer what you need for SoundDrop. As I've understood it, it might turn into quite the interdisciplinary project, so it could be interesting to have a team with one or both students who have experience with something like that: hardware hacking, audio, video, visual art.
Maybe also clarify with all the teams who are interested in applying with SoundDrop that you can/want to only pick one team, and that they might have to withdraw their application and settle for another project. Depending on their experience and interests, you might want to suggest another interesting project from the list to them – other than Lotus and Hoodie, all are pretty much still up for grabs, as far as I can see.

**Comment by starkcoffee** [comment]
Great advice, thank you!

**Comment by alicetragedy** [comment]
:+1:
