### ISSUE TITLE
YAMEM - Yet Another Mass Event Manager

### ISSUE THREAD

**Issue by vircung** [rails-girls-summer-of-code/projects#24]
**Name and Contact of the Project Mentor:** Jacek Nakonieczny @vircung jacek.nakonieczny@gmail.com

**Name of the Project:** YAMEM - Yet Another Mass Event Manager

**Repo URL:** https://github.com/vircung/yamem
**Site URL:** http://yamem.org/

**About the Project:** YAMEM is created to help event organizers to manage information about organized event such as: agenda, organizers, speakers, sponsors etc, and provides data for a dedicated landing page through JSON API

**Suitable for beginners?** Yes. Project originally by a student (also organizer) to manage organization of technical conference for college and high school students ([LDI](http://ldi.org.pl/) and [Check IT](http://checkit.lublin.eu/). More advanced developers can contribute too.

**What are issues/features students may work on?** Improve test coverage, implement new features such as API, improve views, prepare internationalization and translations, extend existing functionalities, prepare sub-domain routing, make it pretty, integrate with external services as Google Maps/Places, refactor existing codebase.

**Comment by alicetragedy** [comment]
Hi @vircung, thank you for your submission of YAMEM for this year's RGSoC. We think your project is an interesting one; but with just one contributor for now, we feel like the project is still a bit too much at its early stages to accept it for this year's program. We're glad to see that you've added better documentation in preparation for the students, though :+1: 
Maybe you would consider submitting again next year?

**Comment by vircung** [comment]
Hey,

Thanks for the response. I see your point. I try to give YAMEM the momentum
too make it at least recognizable. For sure we will meet at next
opportunity :)

2015-03-18 21:19 GMT+01:00 Laura notifications@github.com:

> Hi @vircung https://github.com/vircung, thank you for your submission
> of YAMEM for this year's RGSoC. We think your project is an interesting
> one; but with just one contributor for now, we feel like the project is
> still a bit too much at its early stages to accept it for this year's
> program. We're glad to see that you've added better documentation in
> preparation for the students, though [image: :+1:]
> Maybe you would consider submitting again next year?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/projects/issues/24#issuecomment-83152459
> .

## 

Best regards
Jacek Nakonieczny

**Comment by alicetragedy** [comment]
definitely! :balloon:
