### ISSUE TITLE
Voluntary.Software

### ISSUE THREAD

**Issue by volontarian** [rails-girls-summer-of-code/projects#25]
# Name and Contact of the Project Mentor

Mathias Gawlista (gawlista@gmail.com)
# Name of the Project

Voluntary
# URL

**Source Code of Core:** http://Voluntary.Software 
**Example Provider:** http://Volontari.at (online again)
# About the System

The core is the Ruby gem and [Rails engine](http://guides.rubyonrails.org/engines.html) voluntary which is a crowdsourcing management system with the goal of user-generated content powering http://Volontari.at (German/French for voluntary service or journalism training).

Current "voluntary" plugins alias products are: [recruiting](http://GitHub.com/Volontariat/voluntary) (featured in core product but will be outsourced to new gem volontariat), [text / task creation](http://GitHub.com/Volontariat/voluntary_text_creation), [translation](http://GitHub.com/Volontariat/voluntary_translation), [scholarship](http://GitHub.com/Volontariat/voluntary_scholarship) (multitenant variant of http://Teams.RailsGirlsSummerOfCode.org), [classified advertisement](http://GitHub.com/Volontariat/voluntary_classified_advertisement) and [music metadata enrichment](http://GitHub.com/Volontariat/voluntary_music_metadata_enrichment).
# Suitable for beginners?

Yes, I already participated with this system in Rails Girls Summer of Code 2013 and we released a minimum viable product (MVP) of a new plugin for the system: [classified advertisement](http://GitHub.com/Volontariat/voluntary_classified_advertisement).
# What are issues/features students may work on?

There are many drafts of new plugins as well as new features for already released plugins and core to work on. But for this Summer of Code I would recommend to only work on new plugins implemented as a [Rails engine](http://guides.rubyonrails.org/engines.html) which are as follows ...
## Brainstorming

First "clone" tools like http://Tricider.com. That means managing lists of ideas with pros and cons which are voteable. Maybe there is also time for a comparison feature like http://Versus.io.
This plugin is a dependency of the next product.
## Evaluate.Voluntary.Software

First implement an open source variant of http://Ruby-Toolbox.com which is not only for Ruby Tools.
Not part of the project for this Summer of Code and started when the MVP of dependent brainstorming plugin has been released: brainstorming of different software for a purpose and option to request software.
## Georeferencing

It's about requesting users to add marker(s) about a given topic to a Google map.
## Data Recognition

The customer can define a question about an object like an image and someone of the crowd can complete this task by answering the question.
## Survey

The customer can setup questions with different answering types like Google Form Surveys and define the target audience. And the survey will be shown to the matched crowd and they can answer the questions.
## Tagging

The customer can define data like text or images which should be tagged by the crowd.
## Feedback

Customers can create a project e.g. for a product and users can add feedback like questions, problems, praise and ideas which all are commentable and voteable. Customers can also post announcements here. 
A role model is GetSatisfaction, see it in action here: https://forum.hootsuite.com/hootsuite
## Involuntary

Add new agency model which has many projects and users.
Tasks through those projects should be hidden from voluntary tasks queue even before assignment (involuntary flag).
Assignment of tasks to users (through agencies).
Maybe the students can start an optional accounting system (bounty).

**Comment by anikalindtner** [comment]
hi @volontarian, thanks for submitting the projects. In reviewing it, there were some questions, we had:
- generally what does it do and what are you aiming for? it all seems a bit confusing to us, even the documentation. It seems to be a gigantic app that is similar to our teams.app (https://teams.railsgirlssummerofcode.org/), no?
- in 2013 a RGSoC student worked on this and developed a plugin called disaster assistance for. however we can't find the plugin now. has it ever been merged to voluntari.at? 
- what would the students have to do to have their work merged into the project?
- how many people are contributing to the project?

**Comment by volontarian** [comment]
> generally what does it do? it all seems a bit confusing to us, even the documentation. It seems to be a gigantic app that is similar to our teams.app (https://teams.railsgirlssummerofcode.org/), no?

I'm sorry but there is no real documentation yet, except of short summaries and an [installation guide] for a bumpy start (http://github.com/volontariat/voluntary). 
So it's similar to crowdsourcing platforms like [Amazon Mechanical Turk](http://MTurk.com) (Closed Source) or [PyBossa](http://PyBossa.com) (Open Source) with the difference that not all "applications" are about "assembly-line work". 
With crowdsourcing the customer can divide a big problem (e.g. translating a whole site from one into multiple languages) into microtasks. These microtasks are visible to a (large) group of qualfied people which can complete these tasks. If needed each task can be reviewed / represented by the customer or another person of the crowd. 
I don't know why I not quickly implemented this yet and started it with the [voluntary music metadata enrichment API](https://github.com/volontariat/voluntary_music_metadata_enrichment/wiki/API) some days ago but all task results should be exportable through an JSON API or CSV download.

Such a crowdsourcing platform mostly has some applications which I call products and implement as plugins. All my applications are more or less based on the gem [voluntary](http://github.com/Volontariat/voluntary) and one of those applications is [scholarship](https://github.com/volontariat/voluntary_scholarship/) which is comparable to the "teams.app".
[Volontari.at](http://Volontari.at) is just one provider of a crowdsourcing platform based on the [voluntary gem](http://github.com/Volontariat/voluntary) but in the future maybe a nerve center of all sites using this gem to aggregate data like activities or reputation points.

> in 2013 a RGSoC student worked on this and developed a plugin called disaster assistance for. however we can't find the plugin now. has it ever been merged to voluntari.at? 

As an answer to the question if it's suitable for beginners I linked [the plugin "classified advertisement"](http://github.com/Volontariat/voluntary_classified_advertisement). We decided to implement this more abstract plugin which is also open for the minimum viable product of a disaster assistance project management application through associating a project with an area naming the type of disaster.
It has been already deployed to [Volontari.at](http://Volontari.at): a short user guide which I've just written can be found [here](https://github.com/volontariat/voluntary_classified_advertisement/wiki/Interaction).

> what would the students have to do to have their work merged into the project?

A standard [pull request](http://railscasts.com/episodes/300-contributing-to-open-source) should work. 
Some tests would be nice to see integration problems.

> how many people are contributing to the project? 

Only me :-(

... hope that you are not more confused than before ;-)

**Comment by anikalindtner** [comment]
I'm sorry, this still doesn't help too much with the confusion. The repository, that Carmen did work on during RGSoC 2013, doesn't exist anymore: https://github.com/volontariat/voluntary_disaster_assistance, which is why we can't see what happened here. We also don't quite understand why the the plugin "classified advertisement" has been chosen to replace her work. 

All in all I think it would be great to see your project maybe for next year, but this year it seems too confusing and too spread out for students to work on and have a successful summer. We've raised the bars a bit during the program and have different goals we want to achieve for our students.One main point is that we want already established projects or projects that include a very good documentation as most of our students will be newcomers to the community. At this point, I'm sorry but this project won't qualify for 2015. Please let us know if you have any more questions. We'd be happy to seeing this project moving forward and seeing your application for 2016.

That's why I'm going to close this issue for now.

**Comment by volontarian** [comment]
> We also don't quite understand why the the plugin "classified advertisement" has been chosen to replace her work. 

Her work has been not replaced :-) Before writing any code at our brainstorming event about MVP stories for the summer of code we decided us for this more abstract application: "mother" of a perfect specialized disaster assistance application. So you can find Carmen's work in [this repository](https://github.com/volontariat/voluntary_classified_advertisement/commits?author=mcberros)

> We've raised the bars a bit during the program and have different goals we want to achieve for our students.

Also true for voluntary students?

Anyway thanks for the feedback and see you next year.

**Comment by anikalindtner** [comment]
ah thanks so much for the link to the repository and making some things clearer. 

Yes, the bar is also raised for what we want to achieve for our volunteering students. Thanks so much for understanding!
