### ISSUE TITLE
RubyGameDev.com

### ISSUE THREAD

**Issue by andrewhavens** [rails-girls-summer-of-code/projects#26]
**Name and Contact of the Project Mentor:** Andrew Havens, email@andrewhavens.com

**Name of the Project:** RubyGameDev.com

**URL:** [Homepage](http://www.rubygamedev.com), [GitHub Repo](https://github.com/ruby-rcade/RubyGameDev.com)

**About the Project:**
RubyGameDev.com is a community-driven, information hub which helps others to build games in Ruby. It's a non-commercial, open-source, Rails 4 application that was originally built during the 2013 Rails Rumble. The goal of RubyGameDev.com is to become a valuable, library-agnostic resource to the Ruby programming community. It's meant to help beginners get started with game programming and help advance the quality of Ruby-based game programming libraries through centralized discussion and collaboration.

**Suitable for beginners?** Yes! This project is ideal for beginners as it is a standard Rails application. I have listed a sample schedule below that could be modified based on your experience.

**What are issues/features students may work on?**
There's a lot of work that could be done, which could provide an opportunity for you to choose an area which interests you. There's currently a list of [issues/ideas in the GitHub repo](https://github.com/ruby-rcade/RubyGameDev.com/issues). Here is a sample of some of the features that you could work on:
- Create a digest email of recent activity
- Add a more formal "guides" section for beginners (like Rails Guides)
- Build out the libraries section to be more like ruby-toolbox.com
- Integrate a StackOverflow feed using their API
- Add ability for developers to showcase the games that they've built
- Add ability to post a tutorial, video, slide deck, etc
- Add ability to vote on links
- Lots of other miscellaneous improvements, or add your own to the list!
### Sample Schedule:
1. Learn how to use git
   - Make some updates to the project's `README.md` and learn how to submit a GitHub pull request
2. Learn basic Ruby syntax
3. Learn some basic features of Rails
   - Submit a pull request which implements a small feature or change
4. Learn how to write unit and integration tests
   - Submit a pull request which implements some tests for features that were never tested
5. Try test-driven-development
   - Write tests for the feature you want to implement
   - Implement the feature until your tests pass
   - Submit a pull request
6. Update the project's `README.md` with a review of the things you've learned in order to help someone else get started contributing to the project.
7. Continue to implement features as time allows

**Comment by alicetragedy** [comment]
hi @andrewhavens, first off thank you for your submission. :sparkles: 
As I couldn't find a license for the project, I'd ask you to please add one, as we require it for projects to participate in the Rails Girls Summer of Code. thanks in advance!

**Comment by andrewhavens** [comment]
@alicetragedy Oh! Thanks for pointing that out. I thought I mentioned. Standard MIT License.

**Comment by alicetragedy** [comment]
@andrewhavens no problem, thank you for adding it so quickly. Accepted! We're glad to have you on board :boat: for RGSoC 2015.

**Comment by ghost** [comment]
Hello @andrewhavens My teammate(@essymo) and I would like to work on this project.

**Comment by wontheone1** [comment]
This project sounds really interesting @andrewhavens, can I also work on this project? I have a team mate too.

**Comment by andrewhavens** [comment]
@wontheone1 Thanks for your interest! Send me an email (email@andrewhavens.com) and let me know your skill level, which features/projects you would be interested in, and whether or not you have a coach.

**Comment by babiracka** [comment]
Hello @andrewhavens, I would love to work on this project with my pair @zonderko!

**Comment by yumikohey** [comment]
Hi Andrew, @andrewhavens 
I just sent you an email. My pair and I are interested in working on this project. It sounds so much fun to do it. Looking forward to hearing from you.

**Comment by sandrely2611-zz** [comment]
Hi @andrewhavens! my pair @karenVentura and I are interested in working with you. We're based in Mexico. Still accepting students? We already have our coaches. We'll send you an email :)

**Comment by isatorri** [comment]
Hi @andrewhavens!
I just sent you an email. If you are still accepting students, can we work with your project? Thank you in advance :)

**Comment by VesSun** [comment]
Hello @andrewhavens, me and my teammate (@darzh) would really like to work on your project for RGSoC 2015. It is still available? We also sent you an email, but we haven't gotten a response yet.

**Comment by mimimalizam** [comment]
Hello @andrewhavens! We are also curious as to whether we could apply with your project. We, @Anjazk and I, are motivated to work with you. We have our coaches, too :) Hope to hear from you soon!

**Comment by andrewhavens** [comment]
I regret to announce that I have reached the maximum number of applicants for my project.

--Andrew Havens

**Comment by VesSun** [comment]
Thank you for your response.
All the best and have a nice Summer of Code :)

On Tue, Apr 14, 2015 at 5:44 PM, Andrew Havens notifications@github.com
wrote:

> I regret to announce that I have reached the maximum number of applicants
> for my project.
> 
> --Andrew Havens
> 
> > On Apr 12, 2015, at 5:18 PM, sandramu26 notifications@github.com
> > wrote:
> > 
> > Hi @andrewhavens! my pair @karenVentura and I are interested in working
> > with you. We're based in Mexico. Still accepting students? We already have
> > our coaches. We'll send you an email :)
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/projects/issues/26#issuecomment-92885983
> .

## 

Think _green_.
Every action counts.

_Веселина Агова_
