### ISSUE TITLE
exercism.io

### ISSUE THREAD

**Issue by kytrinyx** [rails-girls-summer-of-code/projects#27]
**Name and Contact of the Project Mentor:** Katrina Owen (@kytrinyx - katrina.owen@gmail.com)

**Name of the Project:** Exercism

**URL:** http://exercism.io

**About the Project:**

Exercism is a web platform for skill development in programming.

It has small programming problems in the form of a README and a test suite. The first goal is to get all of the tests passing. The more interesting part of exercism is the conversation that happens after a solution is submitted. This conversation can take several forms. If the programmer submitting the problem is a beginner, then the feedback often takes the form of help learning the language better. When the programmer submitting the problem is more experienced, the discussion revolves around style, idioms, and best practices. As the code is discussed, the programmer submits new iterations of the solution, evolving and exploring the problem space.

The project lives in the https://github.com/exercism organization. The languages used for the platform itself are Ruby, Go, and Javascript, CSS, and HTML, but each supported language has its own repository containing the problems (test suites) in that language.

**Suitable for beginners?**

Yes, mostly.

The environment is very supportive and friendly. The main code base is somewhat chaotic and unweildy (nature of a prototype, unfortunately), so it can be hard to get started. Other parts of system are quite easy to understand and work in.

**What are issues/features students may work on?**

I am currently working on organizing and defining work. Here are some of the over-arching things that I'd like to achieve in the next few months:
1. Make the project easy to contribute to for people of all skill levels (https://github.com/exercism/exercism.io/issues/2092)
2. Replace the current "pending nitpicks" list with granular subscriptions and an activity stream:
   (https://github.com/exercism/exercism.io/issues/1899)
3. Design and implement a "mentor" feature, allowing a mentor to be notified whenever the mentee submits code (https://github.com/exercism/exercism.io/issues/2248)
4. Improve the onboarding process -- I'm not sure what this means, and I would need help with the entire process: brainstorming, design, product management, implementation.
5. Designing and implementing the dashboard -- again undefined at the moment; this could be a series of small improvements or a big design effort, depending on who gets involved and what they're interested in.

All in all I have far more things to do than people to do them, and I am happy to spend time with students defining and refining ideas.

**Comment by FloorD** [comment]
:bowtie:

**Comment by anikalindtner** [comment]
WOHOO!! so cool @kytrinyx! <3

**Comment by alicetragedy** [comment]
:tada:

**Comment by alicetragedy** [comment]
hey @kytrinyx, we're super happy to have you and exercism.io on board for this year's RGSoC! thank you for your submission :heart:

**Comment by kytrinyx** [comment]
Thanks so much for considering exercism for this.

**Comment by rubydiamond** [comment]
Hello Katrina. I have two students who are looking for a Summer of Code Project here in Los Angles. Is exercism available for a RGSoC project? thejendiamond@gmail.com P.S.- I am running the Rails Girls woorkshop next weekend at Pivotal. I can give them a lot of support this summer but I am also looking for a coaching company for them too.

**Comment by kytrinyx** [comment]
Hi @rubydiamond I work out of the Pivotal LA office. I'll try to stop by while you're here.

I already have 4 teams that have asked and I've told two of them yes (I need to figure out if I can handle a third. I'm not sure how much I can manage on my end, but definitely not 4 or 5.)

**Comment by rubydiamond** [comment]
Are the other teams in Los Angeles?
I can definitely help support my team.

I can also meet up with you any time to discuss it.

---

_Rails Girls LA_
railsgirlsla@gmail.com railsgirls@gmail.com

http://railsgirls.com/la
@RailsGirlsLA

*Jen Diamond *
323-363-0002
thejendiamond@gmail.com
@jendiamond

**Comment by kytrinyx** [comment]
No, one team is in Washington State, one is in Nigeria, one is in Poland, and one I'm not sure. I realized that there's an application process and I'm not really sure how that works.

I can definitely check in with several teams provided that they have good support from their coaches, but I can't do much in terms of management/pairing.

**Comment by kytrinyx** [comment]
Oh, are you in LA/Santa Monica, btw? I'd love to meet up.

**Comment by rubydiamond** [comment]
I'm in Echo Park.

Let's talk on the tele.
email my real email and I'll send you my phone number. :)

---

_Rails Girls LA_
railsgirlsla@gmail.com railsgirls@gmail.com

http://railsgirls.com/la
@RailsGirlsLA

*Jen Diamond *
323-363-0002
thejendiamond@gmail.com
@jendiamond

**Comment by rubydiamond** [comment]
thejendiamond@gmail.com

---

_Rails Girls LA_
railsgirlsla@gmail.com railsgirls@gmail.com

http://railsgirls.com/la
@RailsGirlsLA

*Jen Diamond *
323-363-0002
thejendiamond@gmail.com
@jendiamond

**Comment by rubydiamond** [comment]
We will definitely meet up. :)

**Comment by sandrely2611-zz** [comment]
Hi @kytrinyx! my pair @karenVentura and I are interested in working with you. We're based in Mexico. Still accepting students? We already have our coaches. We'll send you an email :)

**Comment by kytrinyx** [comment]
Hi, thanks for the email. I've reached my limit on how many people I can mentor, unfortunately, and I've already had to turn down 4 teams :(

**Comment by anikalindtner** [comment]
Hi @kytrinyx, then I'll put on the label to show to other students that they shouldn't apply anymore.

**Comment by anikalindtner** [comment]
#### Students: Please don't apply for this project anymore.

**Comment by kytrinyx** [comment]
Thanks @anikalindtner -- I forgot about that label. I should have emailed you!

**Comment by anikalindtner** [comment]
@kytrinyx no worries <3
