### ISSUE TITLE
Rails: ActiveModel::Serializers

### ISSUE THREAD

**Issue by guilleiguaran** [rails-girls-summer-of-code/projects#29]
### Name and Contact of the Project Mentor

Guillermo Iguaran, @guilleiguaran, guilleiguaran@gmail.com
Alexandre de Oliveira, @kurko, chavedomundo@gmail.com
### URL

https://github.com/rails-api/active_model_serializers
### About the Project

ActiveModel::Serializers (AMS) brings convention over configuration to your JSON generation. AMS does this through two components: serializers and adapters. Serializers describe which attributes and relationships should be serialized. Adapters describe how attributes and relationships should be serialized. Right now Rails team is discussing the inclusion of AMS in the next major version of Rails (5.0).
### Suitable for beginners?

Definitely, we have received a lot of contributions of new users and right now we have a small guide for new contributors: https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md
### What are issues/features students may work on?

We would like to receive some help implementing some adapters for hypermedia formats (e.g HAL, Collection+JSON, Siren, JSON-LD, etc), right now the core contributors of the project are focused in JSON API support but we understand the importance of other formats. This is a must-have before of getting ActiveModel::Serializers merged in Rails 5.0.

There are also a lot of small tasks and small PRs pending for review and we would like to receive a bit of help. Other minor tasks related with the integration/merge with Rails 5.0 might araise.

**Comment by sogamoso** [comment]
:+1:

**Comment by robertomiranda** [comment]
:yellow_heart:

**Comment by alicetragedy** [comment]
thank you @guilleiguaran for the submission! We're thrilled to announce that we're accepting this as a project for this year's RGSoC. Whoohoo! thank you so much for being a part of the Rails Girls Summer of Code, we're very excited to have you on board. :space_invader:

**Comment by Heena-Codes** [comment]
Hello @guilleiguaran and @kurko  , me and my pair @keshashah would like to know more about your idea and get involved with it. :+1:

**Comment by keshashah** [comment]
This project looks interesting to me :+1:

**Comment by guilleiguaran** [comment]
@fallacy321 @keshashah thank you so much for your interest, we'll reply you soon via email !!!!

**Comment by guilleiguaran** [comment]
We have received email from two teams interested in this project, so I think we can mark this as "maximum applications reached"
