### ISSUE TITLE
Ruby Object Mapper

### ISSUE THREAD

**Issue by solnic** [rails-girls-summer-of-code/projects#3]
- **Name and Contact of the Project Mentor**: @solnic
- **Name of the Project**: Ruby Object Mapper
- **URL**: http://rom-rb.org
- **About the Project**: Ruby Object Mapper (ROM) is a persistence and mapping toolkit for Ruby that helps in working with various databases and mapping data to ruby objects. It uses a simple adapter layer to connect to different databases and ships with a small infrastructure to encapsulate data access. Supports Rails through rom-rails project and is easy to be used stand-alone too.
- **Suitable for beginners?**: yes and no :) there's always so much to do that everybody should be able to find something to work on regardless of the skills and experience
- **What are issues/features students may work on?** - new adapters for various databases and other datasources (ROM can work with anything that gives data back), improvements in existing infrastructure, documentation, bug fixes, performance improvements...the project is open to all kinds of contributions

**Comment by anikalindtner** [comment]
heja @solnic thanks for the project! 
could you give an email address as well so that students could contact you?

**Comment by solnic** [comment]
oh sorry, I forgot it's not public on gh :) I'm piotr.solnica@gmail.com

**Comment by svenfuchs** [comment]
@solnic :heart:

**Comment by runlevel5** [comment]
@solnic I am no longer a student but :heart: to be one now :)

**Comment by solnic** [comment]
hah such :heart: wow :) ^5

**Comment by anikalindtner** [comment]
@solnic we've approved your project (YAY!) and thank you so much for submitting it. We are looking forward to work together with you <3

### A note to students

If you apply for this project: We think it would be benefitial to have database knowledge, so for beginners it might be a bit challenging, but definitely suitable for more experienced beginners.

**Comment by solnic** [comment]
Fantastic :) Looking forward to it too! :grinning:

**Comment by mimimalizam** [comment]
Hello @solnic! We, me and @anjazk, we have really great coaches, and we would like to apply as beginners to your project if there is place for us.  :/

Hope to hear from you soon :)

**Comment by solnic** [comment]
Totally, welcome on board. Let me know how I can help :)

**Comment by mimimalizam** [comment]
Ok, great! We are little bit short with time. It would be perfect if we could proceed further communication via email (mine is milana.stojadinov@gmail.com). 

We need to make Project Plan in order to submit our application. And that would be our final step.

Thank you!!!
