### ISSUE TITLE
Rubyclerks: Payment module (rails engine)

### ISSUE THREAD

**Issue by rubydesign** [rails-girls-summer-of-code/projects#30]
**Name and Contact of the Project Mentor:** [Torsten Ruger](https://github.com/dancinglightning) torsten@villataika.fi

**Name of the Project:** RubyClerks

**URLs:** 
[github organisation](https://github.com/rubyclerks/) 
[website](rubyclerks.org)
[travis](https://travis-ci.org/rubyclerks/office_clerk)
[code climate](https://codeclimate.com/github/rubyclerks/office_clerk/)

**About the Project:** RubyClerks is a simple e-commerce solution especially for small businesses.
It is characterized by being very simple and thus easy to understand. It is a new rewrite of an old topic, and being new is very much standard rails. Technically it is a collection of rails engines, the core being [office clerk](https://github.com/rubyclerks/office_clerk), and the online shop [sales clerk](https://github.com/rubyclerks/sales_clerk)

**Suitable for beginners?** The project is well structured, documented and tested and so anyone who knows rails can get started very quickly. It will especially teach about rails engines, and will include a wide range of _basic_ rails techniques (backend, controllers,template,some scripting, rspec..), but nothing too complicated.

**What are issues/features students may work on?**
The summer project is a payment module, probably using stripe. [Stripe](https://stripe.com/) is a payment api that is favored by developers for it's clean api.
The module will be implemented as a rails engine and there are templates to make this easier. The module has to integrate with the core, but also provide a small ui that needs to integrate with the online shop extension.

**Comment by alicetragedy** [comment]
hey @dancinglightning, thank you for your submission. We've accepted Rubyclerks as a project for this year's RGSoC, welcome! :tada: I will get in touch with you shortly about the next steps. yay!

**Comment by rubydesign** [comment]
Ok, great.
If someone lives close to Fiskars in Finland, i would consider coaching this too. Just ask.
Torsten

**Comment by anikalindtner** [comment]
<3 <3 <3

**Comment by sandrely2611-zz** [comment]
Hi @dancinglightning! my pair @karenVentura and I are interested in working with you. We're based in Mexico. Still accepting students? We already have our coaches. We'll send you an email :)

**Comment by yumikohey** [comment]
@dancinglightning I want to work on this project. I just sent you an email. Looking forward to hearing from you.

**Comment by alicetragedy** [comment]
#### students: please don't apply for this project anymore, thank you!
