### ISSUE TITLE
RubyGems.org Adoption Center

### ISSUE THREAD

**Issue by qrush** [rails-girls-summer-of-code/projects#31]
**Name and Contact of the Project Mentor**: [Nick Quaranto](mailto:nick@quaran.to), [Benjamin Fleischer](mailto:github@benjaminfleischer.com)
**Name of the Project**: RubyGems.org Adoption Center
**URL**: https://rubygems.org

**About the Project:**

RubyGems needs a way to mark a gem as "maintainer needed" or "someone please take this gem over". This project would drive the creation of an "Adoption Center" (Possibly at http://adoption.rubygems.org) where people could list gems that want a maintainer/someone new to help fix issues, cut releases, etc, and then assist in the handoff of the gem.

Some more background and required reading on this:

https://groups.google.com/forum/#!msg/rubygems-org/niS5ZO9DNgk/5Fhg9Q3QR7YJ
http://www.benjaminfleischer.com/2014/08/17/rubygems-adoption-center/
https://github.com/rubygems/rubygems.org/issues/725

**Suitable for beginners?**

Definitely. I think this could be built as a separate, new Rails app that consumes the [RubyGems.org API](http://guides.rubygems.org/rubygems-org-api). (This could be built into the existing [Rails app](https://github.com/rubygems/rubygems.org) as well, but it might be easier to start with a greenfield app).

**What are issues/features students may work on?**

All of it! We have a lot of spec ideas/features written out but zero code thus far. We are happy to help review and work with anyone who's interested in making this real.

cc @bf4 (want to be listed as a mentor/contact? :grin: )

**Comment by bf4** [comment]
Sure :)

**Comment by qrush** [comment]
Updated.

**Comment by alicetragedy** [comment]
thank you for your submission @qrush. we'd be very happy to accept this RubyGems Adoption Center as a project; though we don't usually accept "original" projects, we think it's a great idea, certainly see the need for it, and think that it would be an awesome contribution to our community. So, without further ado.. welcome! :tada: :balloon:

**Comment by qrush** [comment]
Thanks @alicetragedy  - not sure what you mean by "original" though. Maybe there's something I could clarify?

**Comment by alicetragedy** [comment]
@qrush by "original" we mean a completely new project that doesn't exist yet, doesn't have a repo or contributors, and that is just a simple idea that needs to be worked on. This is mainly to avoid students working on a project for three months that might end up going nowhere and not be useful to the community at all. Does that make sense?
I know that in your case, it is more of a feature to an existing project rather than a completely new project, so I suppose it would not necessarily count as an "original" project anyway. :) but I just wanted to point it out nevertheless.

**Comment by qrush** [comment]
Ah cool. Yeah, I'd say this is more of a feature for an existing repo. In fact it would probably be better to keep it in the existing Rails app, and we could split it out later. I'm mostly not trying to lock down exactly what the implementation will be.

**Comment by alicetragedy** [comment]
don't worry, not trying to lock it down makes total sense to me. 
I'll be in touch with you and @bf4 in the next couple of days to give you some information so you have an idea of which things you need to discuss with interested teams and of how the student application process works.

**Comment by agbinary** [comment]
Hi @qrush , my pair and I are interested in your project and we wanna get involved

**Comment by qrush** [comment]
Cool! Sounds good. I don't think any others have applied yet.

@alicetragedy - do we wait until the deadline (4/14) to get started, I assume?

**Comment by alicetragedy** [comment]
Hi @qrush, you should have gotten an email from me with general infos about the process; the students need a project plan to apply with (by April 14th) so in the next few days, you can help @angela4713 and her pair with this. It should be a basic description of what will need to be done / a proposed timeline for the summer. We understand that the timeline might change throughout the summer, but it's a way for us to see that the students have understood the requirements of the project and have set goals accordingly. :)

**Comment by alicetragedy** [comment]
@angela4713 feel free to contact Nick and Benjamin by email to get started, so you can have a finished project plan by the deadline. Ping us if you have any questions, we've also set up a slack channel for support questions, the link is on Facebook and twitter. Good luck!

**Comment by qrush** [comment]
Thanks @alicetragedy.

@angela4713 (and anyone else), I'd start by reading the "background" links up above...if you have any questions I'd be happy to answer them too.

**Comment by raluka** [comment]
Hello Nick Quaranto and Benjamin Fleischer,
We are Thuy (@1000miles), and Raluca (@raluka), and our amazing team R'n B (Ruby and Bugs) would love to contribute to your project during Rails Girls Summer of Code. We hope we are not too late to apply for it!
We will send you a separate email to ask you for details. 

Best wishes from the R'n B Team!

**Comment by alicetragedy** [comment]
### Students: please don't apply for this project anymore. Thank you!
