### ISSUE TITLE
Recipe Guru

### ISSUE THREAD

**Issue by anujaware** [rails-girls-summer-of-code/projects#35]
- **Name and Contact of the Project Mentor:** Shweta Kale (shweta@joshsoftware.com), Anuja Ware  (anuja@joshsoftware.com)
- **Name of the Project:** Recipe Guru
- **URL:**  https://github.com/Shwetakale/recipe_guru.git , http://recipe-guru.herokuapp.com/
- **About the Project:** This project is all about get different and yummy recipes, share your recipes, rate and comment on recipes.
  - You can get different recipes here without registration.
  - You need to sign up to share your recipes.
  - Recipe will contain Title, Description, Pre Requirenments, Ingredients, Recipe/Steps, Images, Benefits.
  - Recipe/Steps - We have provided an editor to add your recipe using which you can decorate your page.
  - Ingredients - Select from list and specify quantity and other details about ingredient for e.g. Onion - 1 - Chopped
  - Images - You can upload as many images as you want to show with your recipe. These image will be display one by one on the page.
  - You can rate or comment on particular recipe after sign in.Currently user can register, login, add a post (description and photo mainly), add comments.
- **Suitable for beginners?:** Yes
- **What are issues/features students may work on?:** There are many open issues for beginners from which they can learn more things. Some of them are - Social media integration - S3 integration for uploading image - Adding some intresting functionality - Adding newsletter - Adding Test cases and many more.. Please check issue list

**Comment by carpodaster** [comment]
Thank you for your project submission, @anujaware. We think your project is an interesting one and indeed very beginner friendly.

However, with the first commit being made only about a month ago and only two contributors so far, we feel like the project is still a bit too much at its early stages to accept it for this year's program. Maybe you would consider submitting again next year?
