### ISSUE TITLE
LivingStyleGuide

### ISSUE THREAD

**Issue by hagenburger** [rails-girls-summer-of-code/projects#37]
## Name and Contact of the Project Mentor:

Nico Hagenburger, [@hagenburger](https://github.com/hagenburger)/[@hagenburger](https://twitter.com/hagenburger)/[@hagenburger](https://dribbble.com/hagenburger), [n…o@h…r.net](http://www.hagenburger.net/CONTACT.html)
## Name of the Project:

LivingStyleGuide
## URL:
- https://github.com/hagenburger/livingstyleguide/tree/v2
- http://livingstyleguide.org
- https://twitter.com/LSGorg
## About the Project:

Easily create living style guides/front-end style guides/pattern libraries by adding Markdown documentation to your Sass project. This library is used by [Eurucamp](http://style-guide.eurucamp.org/latest/) and OpenProject as well as many start ups and other web projects.

Currently version 2 is in the making having some major refactoring. This will be done within the next weeks.
## Suitable for beginners?

Yes, the code is kept simple with few dependencies (learning how [Tilt](https://github.com/rtomayko/tilt) works would be part of the project). Tests are written. An interest in front-end topics, CSS and Sass is helpful. Having fun in writing beautiful code and creating beautiful output in the browser would be great.
## What are issues/features students may work on?

All features/plans/bugs are are listed as GitHub issues: https://github.com/hagenburger/livingstyleguide/issues.
All v2.0.0 tasks should be done soon before the summer begins. To list some tasks to work on:
- Add new features like (from simple to complex):
  - [Allow to copy out of the style guide](https://github.com/hagenburger/livingstyleguide/issues/24)
  - [Automatically generate a navigation](https://github.com/hagenburger/livingstyleguide/issues/72)
  - [Search](https://github.com/hagenburger/livingstyleguide/issues/42)
  - Create an extension API and implement e.g. the search and navigation as extension (so different kinds of navigations could be used)
  - [Improve error handling](https://github.com/hagenburger/livingstyleguide/issues/121)
- Moving to documentation from the readme into a well-formated documentation on livingstyleguide.org
- Some big tasks that are not planned but requested could be done if the team is interested:
  - Support for Libsass
  - Support for other preprocessors

But I’m happy to discuss with the applications about their personal interests what task match the most :)

**Comment by alicetragedy** [comment]
whoohoo @hagenburger! Thank you for your submission. We think this would make a great project for the Rails Girls Summer of Code, and we're happy to officially accept you for this year's program! I'll send you an email soon with all the important information you need to know. :tada: :sparkles:

**Comment by hagenburger** [comment]
@alicetragedy great news! I’m happy to be able to be a little part of it :) Thank you!

**Comment by anjalyes** [comment]
@hagenburger hey me and my pair are intersted in working with this project. Is the application still open?

**Comment by hagenburger** [comment]
@anjalyes I got one more request via email, but nothing is set yet :)

**Comment by Xteff** [comment]
Hi @hagenburger. We are the **Fanxhe Team**, we already contacted you via e-mail, just to let you know that we just sent an updated proposal :smile:

**Comment by hagenburger** [comment]
Hi and welcome @freewomancode :)
