### ISSUE TITLE
Lotus

### ISSUE THREAD

**Issue by jodosha** [rails-girls-summer-of-code/projects#4]
**Name and Contact of the Project Mentor:** Trung Lê (@joneslee85), email: trung.le@ruby-journal.com

**Name of the Project:** Lotus

**URL:** http://lotusrb.org

**About the Project:** It's a lightweight, complete web framework for Ruby. We'd love to have help because we have plenty of features to add and we are [student friendly](http://bitboxer.de/2014/10/26/teaching-ruby/).

**Suitable for beginners?** Yes. Both beginners and more experienced students could work on this. In the past, both Luca (@jodosha) and Trung (@joneslee85) mentored developers at their first OSS contribution.

**What are issues/features students may work on?** We're moving fast with features, and the priority changes according to the real world needs of the companies that are adopting Lotus. So it's hard to make a commitment a few months in advance. We have a [roadmap](http://bit.ly/lotusrb-roadmap) that includes tasks with different level of complexity: we can plan with the student. Some of those include helpers, assets management, security, model associations, HTTP streaming, documentation, JS integration, etc..

**Comment by svenfuchs** [comment]
@jodosha :heart:

**Comment by jodosha** [comment]
@svenfuchs :heart:

**Comment by anikalindtner** [comment]
Thanks for submitting the project! It sounds awesome. Approved :)

**Comment by jodosha** [comment]
@anikalindtner awesome, thank you!

**Comment by runlevel5** [comment]
@anikalindtner thanks :) looking forward to another great RGSoC

**Comment by alicetragedy** [comment]
glad to see this on the list after your talk at vienna.rb, @jodosha! :sparkles:

**Comment by jodosha** [comment]
@alicetragedy Thank you. It was great to talk there. I hope to join a meetup in person in the near future.

**Comment by inescoelho** [comment]
Hi! I just want to let you know that we contacted you via email!
