### ISSUE TITLE
Open Source Event Manager

### ISSUE THREAD

**Issue by hennevogel** [rails-girls-summer-of-code/projects#5]
- **Name and Contact of the Project Mentor**: @hennevogel / hvogel@opensuse.org
- **Name of the Project**: Open Source Event Manager
- **URL**: http://osem.io
- **About the Project**: OSEM is an event/conference management app tailored to Free Software conferences. It helps volunteer event organizer teams with paper submission, scheduling, marketing and analytics.
- **Suitable for beginners?**: Yes. We already have participated three times with GSoC. Last year with 3 students/projects.
- **What are issues/features students may work on?** From simple [features](https://github.com/openSUSE/osem/issues?page=1&q=is%3Aopen+is%3Aissue+label%3AFeature) like adding personalized schedules, over more design/ux focused things like ramping up the user onboarding, to refactor the current code for things like strong parameters. We have it all ;-)

**Comment by anikalindtner** [comment]
Hey @hennevogel thanks for submitting your project! We've accepted it for 2015 \o/

**Comment by hennevogel** [comment]
Awesome! The whole team is looking forward to it. Is there anything we can do for now? :dancers:

**Comment by anikalindtner** [comment]
@hennevogel other than reading the [guide](http://railsgirlssummerofcode.org/guide/projects) carefully and contact us with ALL the questions you might have, probably not much. But spreading the word about this Call for Projects and Rails Girls Summer of Code would be awesome. If it's over mailing lists, your local user group or your friends: This helps a lot :heart:

**Comment by hennevogel** [comment]
I see what I can do. Thanks again! :tada:

**Comment by hennevogel** [comment]
Here are a couple of suggestions for features that you could implement during RGSoC:
- A [post-conference dashboard](https://github.com/openSUSE/osem/issues/462) in combination with [feedback questionnaires](https://github.com/openSUSE/osem/issues/549)
- An [Individual User Schedule](https://github.com/openSUSE/osem/issues/587)
- Features for the conference splash page [#574](https://github.com/openSUSE/osem/issues/574),[#591](https://github.com/openSUSE/osem/issues/591),[#545](https://github.com/openSUSE/osem/issues/545) and [#400](https://github.com/openSUSE/osem/issues/400)
- [Make it possible to 'theme' OSEM](https://github.com/openSUSE/osem/issues/243)
- [Send useful mails to visitors](https://github.com/openSUSE/osem/issues/105) and [notify people about comments](https://github.com/openSUSE/osem/issues/15)

**Comment by hennevogel** [comment]
[Team Falcons](https://teams.railsgirlssummerofcode.org/teams/26) is proposing to work on the _individual user schedule_ and [Team RailsGirlsPL](https://teams.railsgirlssummerofcode.org/teams/20) is proposing to work on the _post-conf dashboard_.

As the OSEM hackers are not going to be able to mentor more than 3 teams, there is only one potential slot left. Hurry up! :runner: :neckbeard:

**Comment by 1000miles** [comment]
Hi @hennevogel, @raluka and me (@1000miles) would love to work on your project. We will send you a separate email to ask you for details. We hope that we are not too late to apply for your project. :)

Here is our team page:
https://teams.railsgirlssummerofcode.org/teams/39

Best wishes from the R'nB (Ruby & Bugs) Team
Thuy

**Comment by soff22** [comment]
Dear Henne,
me and my teammate Boryana also would like to apply for your project. I do hope that it is not late to join. 
Please inform us if we can announce it for a project and further I will send you additional e-mail.
Thank you
Kind regards,
The RailsGi Enthusiasts Team

**Comment by sandrely2611-zz** [comment]
Hi @hennevogel! my pair @karenVentura and I are interested in working with you. We're based in Mexico. Still accepting students? We already have our coaches. We'll send you an email :)

**Comment by hennevogel** [comment]
@1000miles, @soff22 and @sandramu26 I have answered your private mails, good luck applying! :-) 

**everyone** there are now a lot of teams thinking about applying to RGSoC@OSEM, I guess it's probably the best idea to check for another project in the issues, sorry.

**Comment by anikalindtner** [comment]
#### Students: Please don't apply for this project anymore.

**Comment by soff22** [comment]
Hi Anika,
I have just received an e-mail from Henne that our team can apply. 
Please advise as I am going ti write this project in our app form.

Thank you
Kind regards,
Sophia

**Comment by anikalindtner** [comment]
@soff22 If he could still accept you, that is totally fine. He also mentioned you in the comment before, did you see? It's just a note to all the other students who haven't applied yet for this project.
