### ISSUE TITLE
Bundler

### ISSUE THREAD

**Issue by indirect** [rails-girls-summer-of-code/projects#6]
Name and Contact of the Project Mentor: André Arko, @indirect, andre@arko.net

Name of the Project: Bundler

URL: http://bundler.io

About the Project: Ruby dependency manager and gem development tool

Suitable for beginners? I believe so. We've put a lot of work into [instructions anyone can use to get started](https://github.com/bundler/bundler/blob/master/CONTRIBUTING.md#contributing).

What are issues/features students may work on?  I'm happy to find issues or features appropriate for the level of any applicant, but I don't want to do that work now. Last year I did a lot of advance planning that was wasted when no teams I had worked with were accepted. We run a team Slack instance where the team chats on a daily basis, and we use [the Bundler Trello board](https://trello.com/b/DioUaKgx/bundler) to track features that we're interested in implementing soon. There's a lot of options depending on the skill level and ambition of the applying team. :)

**Comment by svenfuchs** [comment]
@indirect :heart:

**Comment by anikalindtner** [comment]
Hey @indirect thanks so much for submitting. To an amazing RGSoC 2015! \o/

**Comment by gabrielanavarro** [comment]
@indirect I would like to participate in this project.  Can you tell me what I can do to participate?

**Comment by indirect** [comment]
@gabrielanavarro sure, just send me an email introducing yourself and your pair, and we can figure out what kinds of things Bundler has to do that your team can work on!
