### ISSUE TITLE
Official Ruby Documentation Redesign

### ISSUE THREAD

**Issue by zzak** [rails-girls-summer-of-code/projects#7]
Name and Contact of the Project Mentor: Zachary Scott, @zzak, zzak@ruby-lang.org, e@zzak.io

Name of the Project: Official Ruby Documentation Redesign

URL: http://docs.ruby-lang.org/

About the Project: Design an attractive and useful template for reading Ruby documentation, made available as the official ruby-lang.org language reference documentation.

Suitable for beginners? Requirements would include:
- Running commands in CLI for generating RDoc
- Downloading project and Ruby repository for generating docs
- Modifying Ruby (ERB-like) templates for HTML, CSS, Javascript

What are issues/features students may work on?

Students would be designing and implementing a new template for the English documentation for ruby-lang.org. Ideally we would start from the existing template, since it already has some nice features baked in, such as: searchable content, and enhanced accessibility for screen-readers. These are important features that would need to remain supported in the re-design.

**Comment by pxlpnk** [comment]
<3

**Comment by svenfuchs** [comment]
@zzak :heart:

**Comment by fxn** [comment]
:heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:

**Comment by FloorD** [comment]
:stars:

**Comment by anikalindtner** [comment]
awesome, @zzak. Thanks for submitting. Accepted \o/

**Comment by zzak** [comment]
Woooooo <3

**Comment by arianepaola** [comment]
Hello @zzak 

Our team, Ramya @Aumrr and Ariane @arianepaola would love to work on this project.

Thanks, Ariane

**Comment by zzak** [comment]
@arianepaola @Aummrr Great!

How do we proceed?

**Comment by arianepaola** [comment]
@zzak do you have any other requirements for the project than above? 

We saw that Ruby is mirrored to github, but could not find the entry point for the rdoc files and templates. There is probably more to it, than just calling RDoc for all files :-)

Ruby on Rails also uses RDoc and their template is nice http://api.rubyonrails.org/

We also saw http://ruby-doc.org/ which is linked from the official Ruby website. How is it involved or are these two different documentations?

Thanks, Ariane

**Comment by zzak** [comment]
@arianepaola Let's chat about requirements over email, but to answer your questions:

The generator for docs.ruby-lang.org is here, this is mostly just some Rake tasks to use RDoc on ruby source for various branches and releases:
https://github.com/ruby/docs.ruby-lang.org

The documentation template for api.rubyonrails.org uses `sdoc`:
https://github.com/voloko/sdoc

Sdoc is really just an RDoc plugin, much like the other templates for Rdoc (darkfish), it can generate the HTML for us.

ruby-doc.org is not maintained by us, but rather a 3rd-party. It is nice, but I think we can make a really awesome website to be the official location for Ruby docs!
