### ISSUE TITLE
diaspora*

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/projects#8]
**Name and Contact of the Project Mentor:** Lisa Passing, email: mail@lislis.de, twitter: @lisapassing  
**Name of the Project:** diaspora\*  
**URL:** https://diasporafoundation.org/  
**Github:** https://github.com/diaspora/diaspora  
**About the Project:** diaspora\* is a privacy aware, decentralized, federated social network and, of course, open source. You can host your own server or join a community server ([list of community servers](http://pods.jasonrobinson.me/])). 
Fun fact: this is the 3rd year diaspora\* runs as a Rails Girls Summer of Code project!  
**Suitable for beginners?** Definitely! There is a wide range of issues suitable for all experience levels. There is also a special [newcomer tag](https://github.com/diaspora/diaspora/issues?q=is%3Aopen+is%3Aissue+label%3Anewcomer) to help new developers get started. Plus, the community and the developers are super nice people!
**What are issues/features students may work on?** Development happens entirely on github. So all the possibilities are [in the issue tracker](https://github.com/diaspora/diaspora/issues?q=is%3Aopen+is%3Aissue). This includes, but is not limited to working on the mobile app, fixing ui bugs, writing documentation, improve tests, translating things, refactoring and implementing features.  
Ping me for further questions :)

**Comment by alicetragedy** [comment]
:two_hearts:

**Comment by svenfuchs** [comment]
@lislis :heart:

**Comment by zzak** [comment]
:muscle:

**Comment by alicetragedy** [comment]
yay, so glad to have you and diaspora\* on board again this year, @lislis! :tada:

**Comment by lislis** [comment]
Yay! Thanks a bunch :D

**Comment by aberracja** [comment]
@lislis me and my pair are totally interested at diaspora! Please read email from us :)

**Comment by anikalindtner** [comment]
#### Students: Please don't apply for this project anymore.
